// Date formats
export enum DateFormats {
  FORMAT_YYYY_MM_DD = 'YYYY-MM-DD',
  FORMAT_YYYYMM = 'YYYYMM',
  FORMAT_YYYY_MM = 'YYYY-MM',
  FORMAT_MM_YYYY = 'MM/YYYY',
  FORMAT_DD_MM_YYYY = 'DD/MM/YYYY',
  FORMAT_DD_MM_YYYY_HH_MM_SS_HYPHEN = 'DD-MM-YYYY HH:mm:ss',
  FORMAT_DD_MM_YYYY_HH_MM_SS = 'DD/MM/YYYY HH:mm:ss',
  FORMAT_YYYY_MM_DD_HH_MM_SS = 'YYYY-MM-DDTHH:mm:ss',
  FORMAT_DD = 'DD',
}
